package com.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.crypto.spec.IvParameterSpec;
import java.io.Serializable;

@DynamoDBTable(tableName = "Secret")
public class Secret implements Serializable {
    private String id;
    private String userId;
    private String name;
    private String content;
    private IvParameterSpec initializatonVector;

    public Secret() {}

    public Secret(String userId, String name, String content) {
        this.userId = userId;
        this.name = name;
        this.content = content;
    }

    @DynamoDBHashKey()
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @DynamoDBAttribute
    public IvParameterSpec getInitializatonVector() {
        return initializatonVector;
    }

    public void setInitializatonVector(IvParameterSpec initializatonVector) {
        this.initializatonVector = initializatonVector;
    }
}
