package com.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.List;

@DynamoDBTable(tableName = "Secret")
public class Secret implements Serializable {
    private String id;

    private String userId;
    private String name;
    private String content;
    private List<Byte> seed;

    public Secret() {}

    public Secret(String userId, String name, String content) {
        this.userId = userId;
        this.name = name;
        this.content = content;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId")
    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"userId"})
    public String getUserId() { return userId; }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @DynamoDBAttribute
    public List<Byte> getSeed() {
        return seed;
    }

    public void setSeed(List<Byte> seed) {
        this.seed = seed;
    }

    @Override
    public String toString() {
        return "Secret{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", name='" + name + '\'' +
                ", content='" + content + '\'' +
                ", seed=" + seed +
                '}';
    }
}
